# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='the_list',
        ),
    ]
