# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20170506_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 6, 19, 19, 31, 250000)),
        ),
    ]
