# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20170506_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
